### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by Fachmann04** [orsalmon/ins-gps-ekf#1]
I am not really getting smart from your code as I don't understand where I have to input the data from IMU and GNSS. Could you please provide an example on how to use the functions and where I have to do something myself? That woul be very kind.

**Comment by orsalmon** [comment]
Hi,

The ins-gps-ekf is a c++ library with very simple API:
1. create an instance of EKF_INS::EKF();
2. input initial conditions using setInitialState(Eigen::Vector3d p_0,
Eigen::Vector3d v_0, Eigen::Matrix3d T_0);
3. when you want to start, run start();
4. whenever you have data from the accelerometer, use
updateWithInertialMeasurement(Eigen::Vector3d data, enum Type type); ,
where type = EKF_INS::Type::ACCELEROMETER
5. whenever you have data from the gyro, use
updateWithInertialMeasurement(Eigen::Vector3d
data, enum Type type); , where type = EKF_INS::Type::GYRO
6. whenever you have data from the GPS, use updateWithGPSMeasurements
(std::vector<Eigen::Matrix<double, 6, 1>> gps_data);
7. to get the output of the ekf you can use one of those methods:
Eigen::VectorXd getErrorState();
std::tuple<Eigen::Vector3d, Eigen::Vector3d, Eigen::Matrix3d>
getNavigationState();
Eigen::MatrixXd getErrorStateCovariance();
Eigen::Vector3d getPositionState();
Eigen::Vector3d getVelocityState();
Eigen::Matrix3d getOrientationState();
double getAzimuth();
You can take a look in
https://github.com/orsalmon/KittiDatasetGPS-INSViewer/blob/master/KittiDatasetTools/KittiDatasetParser.cpp,
especially in the function void KittiDatasetParser::startPlayingData(); to
see how I am using this library.

Have a nice day,
Or

**Comment by Fachmann04** [comment]
Thanks a lot!
